server:
  port: 8801

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1.com:7001/eureka/,http://eureka-server2.com:7002/eureka/