server:
  port: 8801

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server1.com:7001/eureka/,http://eureka-server2.com:7002/eureka/

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000