server:
  port: 8803
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 172.17.0.3
      port: 8500
      discovery:
        service-name: ${spring.application.name}
