server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server1.com:7001/eureka/,http://eureka-server2.com:7002/eureka/

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: com.hachi.cloud.entity